matas70/matas

- data/aircrafts-info.json
- data/aircrafts.json
- js/functions.js
- js/popups.js
- change location "until" paramter to be "from".
- make simulation starts at 110 minutes constantly. (remove this later).
> - added more shows

- css/map.css
- js/HTMLMarker.js
- js/functions.js
- js/map.js
- js/markerclusterer.js
1. Fix HTML Marker so it will draw on top of the overlayLayer instead of the overlayImage.
2. Fix MarkerClusterer so it will draw on top of the overlayLayer instead of the mouseOverlay.
3. Support zIndex for MarkerClusterer.
4. Set all zIndex values properly on maps.js.
> make aircrafts appear on top of locations, to do this I needed to:

- js/HTMLMarker.js
- js/map.js
- js/markerclusterer.js
1. visible layer that doesn't receive DOM events.
2. invisible layer that receives DOM events.
this way the location point can be drawn beneath the aircrafts but still get click events.
> fix HTMLMarker and MarkerCluster to have two layers:

- js/functions.js
2. make simulation restart when no more aircrafts.
> 1. added images for ground shows.

- data/aircrafts.json
- data/config.json
- js/functions.js
- js/popups.js
2. changed show time to 2 minutes intead of 10.
3. reduced crowding popup schedule to 30 seconds.
> 1. moved crowding text to a separated config file.

- main.css
הי @Ofiri93 
בטעות הרסתי לך את הפיצ'ר, מצ"ב תיקון
סליחה
נעם
> fix: reset button on supporting devices (עבודה של אופיר)

- index.html
- js/popups.js
> Revert "fix ar links on banner also"

- index.html
- js/popups.js
> Revert "fix href on banner"

- index.html
- js/popups.js
> Revert "changed ar to be opened by href"

- index.html
- js/popups.js
> Revert "changed ar.html to be opened by href"

- Web.config
> Revert "feat: create redirects"

- .gitignore
- ar.html
- js/quiz.js
> track quiz interactions using gtag (Google Analytics tag)

- index.html
אני לא בטוחה אם זה פתר את זה כי כרגע הפופ הזה לא נראה באתר
> fixed bug so it will send to usdz model

- ARButton.js
- ar.html
- css/AR.css
- main.css
משימות(לפי סדר עדיפויות)
`*להפוך את הטוגל לעבוד כמו טוגל ולא כמו כפתור || תוקן`
`*להחזיר את הפונקציה של הסגירה שהAR יסגר נכון  || תוקן`
`*לתת לפופאפ הסבר של AR כמה שניות לפני שהוא עולה || תוקן`
`*לתת לפופאפ מסך מלא כמה שניות לפני שהוא עולה|| תוקן`
`*להוריד צבע בלחיצה של הטוגל || תוקן`
*לשנות שהכניסה ממטוסים שונים תפתח אותם הAR***אפתח לזה פול רקווסט אחר"""
*לתקן שהמטוס בVR לא יהיה גדול כשחוזרים***אפתח לזה פול רקווסט אחר"""
אפשר לעשות לזה מרג'
> small fix of bugs and style in ar

- css/map.css
- main.css
משימות :
`*להוסיף אנימציית דהייה ל usdz popup || תוקן`
`*לתקן את הבאג של הזזת המסף הצידה בar  || תוקן`
> css fix in ar

- ar.html
- js/functions.js
- js/popups.js
- main.css
משימות :
`*להוריד את העזרה בAR|| תוקן`
`*לשנות את המלל של הפופ אפ הנתמך|| תוקן`
`*בלחיצה על העזרה שיפתח בדיוק את אותו הפופ אפ בלי כותרת עזרה || תוקן`
> remove help option from ar and fix in popup

- service-worker.js
let's hope this commit will clear the PWA cache
> fix: clear cache (hopefully)

- js/functions.js
מוריד את הנצ של 'המתנות מוזיאון' מהישובים
> fix bug with 'המתנות מוזיאון'

- ar.html
- js/functions.js
- js/popups.js
- js/quiz.js
הרחבת הניטור של התנהגות המשתמשים במערכת -
* בחירת מטוסים בAR, יציאה מהAR, שיתוף של הAR (כולל העתקת קישור לclipboard בדפדפנים לא תומכים), כניסת AR למסך מלא, לחיצות על אייקון העזרה
* ניטור כשלונות של טעינת google maps
* ניטור לחיצת כפתור הבית (לפקס את המפה על מיקום נוכחי) - עובד \ לא עובד בגלל הרשאות \ לא עובד בגלל תמיכת דפדפן
* ניטור כניסה לusdz-ים - באיזה מטוסים צופים
* ניטור מונחי חיפוש - אם המשתמש מקליד טקסט, שולחים לgoogle analytics מה הוא חיפש
* ניטוי ניקוי תיבת חיפוש - כפתור x וכפתור ביטול
* ניטור בסיסים פתוחים - על איזה בסיסים פתוחים הסתכלו
* תיקון ניטור החידון - איזה שאלות ענו נכון ולא נכון, וכמה נקודות אנשים הוציאו
* ניטור שיתוף חידון
> feat: add gtags to AR

- js/functions.js
Pop closes faster if no audio message for aircraft
> feature: notify user logic change

- js/functions.js
- js/map.js
- js/popups.js
- js/press.js
1. הtype והhidden לא אמורים להידרס ע"י הroutes. עשיתי שהם לא יידרסו
2. עכשיו כשהtype תקין, אפשר להשתמש בו במקום לפלטר לפי המחרוזות
> Hotfix: data consistency

- js/functions.js
הבעיה - מי שראה הודעת "ברוכים הבאים" ב2019 לא יראה אותה ב2022.
הפתרון - משתנה localstorage מעודכן ל2022, יוודא שכל משתמש יראה השנה את הברכה
> fix welcome 2019 to 2022

- ar.html
> perf: move AR models to storage

- js/HTMLMarker.js
on location now does not close right after click
> hotfix: on location click 

- css/map.css
- js/functions.js
- js/popups.js
should work perfectly when noam release his pr which fix problem with base type
> Fix plunter meir

- .github/workflows/playwright.yml
- .gitignore
- example.har
- package-lock.json
- package.json
- playwright.config.ts
- tests/ar.spec.ts
- tests/common.ts
- tests/example.spec.ts
- tests/open-bases-popup.spec.ts
- tests/quiz.spec.ts
- tests/view-aircraft.spec.ts
כרגע בפרוייקט של המטס אין בדיקות אוטומטיות.
אני מאמין שזה חוב טכני - בדיקות אוטומטיות יורידו את הסיכון בהמשך הפיתוח :smiley:
> e2e testing automation

- js/press.js
- press.html
- press.html עובד - נפתח בטלפונים 
- לתקן נראות הקובץ(css)
לא לעשות מרג
> remove(function that redirect to main page if phone)
